package com.id.administrasikaligentong.content

import com.id.administrasikaligentong.entity.DocumentEntity
import com.id.administrasikaligentong.entity.DocumentFormEntity
import com.id.administrasikaligentong.util.InputType
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.util.*

object Data {

    private val today = LocalDate.now().format(DateTimeFormatter.ofPattern("dd MMMM yyyy")
        .withLocale(Locale("in", "ID"))
    )

    val suratKeteranganList = listOf(
        DocumentEntity("Surat Keterangan Umum", "surat_keterangan_umum.pdf", listOf(
            DocumentFormEntity("Nama Lengkap", "nama"),
            DocumentFormEntity("Tempat dan tanggal lahir", "tempat_tanggal_lahir"),
            DocumentFormEntity("Warganegara", "warga_negara"),
            DocumentFormEntity("Agama", "agama"),
            DocumentFormEntity("Pekerjaan", "pekerjaan"),
            DocumentFormEntity("Tempat tinggal", "alamat"),
            DocumentFormEntity("NIK", "nik"),
            DocumentFormEntity("No. KK", "no_kk"),
            DocumentFormEntity("Keperluan", "keperluan"),
            DocumentFormEntity("Berlaku Dari", "berlaku_dari"),
            DocumentFormEntity("Berlaku Hingga", "berlaku_hingga"),
            DocumentFormEntity("Keterangan lain", "keterangan", inputType = InputType.MultiLine(50)),
            DocumentFormEntity("Tanggal Tanda Tangan", "tanggal_ttd", today),
            DocumentFormEntity("Nama Kepala Desa", "nama_kades"),
            DocumentFormEntity("Nama Pemohon", "nama_pemohon"),
            )),
        DocumentEntity("Surat Keterangan Tidak Mampu", "surat_keterangan_tidak_mampu.pdf", listOf(
            DocumentFormEntity("Nama Lengkap", "nama"),
            DocumentFormEntity("Jenis Kelamin", "jenis_kelamin"),
            DocumentFormEntity("Tempat/Tanggal Lahir", "tempat_tanggal_lahir"),
            DocumentFormEntity("Warganegara/Agama", "warga_negara_agama"),
            DocumentFormEntity("No. KTP/NIK", "nik"),
            DocumentFormEntity("Pekerjaan", "pekerjaan"),
            DocumentFormEntity("Alamat", "alamat", inputType = InputType.MultiLine(35)),
            DocumentFormEntity("RT", "ketua_rt"),
            DocumentFormEntity("Nomor Surat Keterangan dari Ketua RT", "nomor_surat_rt"),
            DocumentFormEntity("Tanggal Surat Keterangan dari Ketua RT", "tanggal_surat_rt"),
            DocumentFormEntity("Permohonan", "untuk_permohonan", inputType = InputType.MultiLine(70)),
            DocumentFormEntity("Tanggal Tanda Tangan", "tanggal_ttd", today),
            DocumentFormEntity("Nama Kepala Desa", "nama_kades"),
        )),
        DocumentEntity("Surat Keterangan Usaha", "surat_keterangan_usaha.pdf", listOf(
            DocumentFormEntity("Nama Lengkap", "nama"),
            DocumentFormEntity("Jenis Kelamin", "jenis_kelamin"),
            DocumentFormEntity("Tempat/Tanggal Lahir", "tempat_tanggal_lahir"),
            DocumentFormEntity("Warganegara/Agama", "warga_negara_agama"),
            DocumentFormEntity("No. KTP/NIK", "nik"),
            DocumentFormEntity("Pekerjaan", "pekerjaan"),
            DocumentFormEntity("Alamat", "alamat", inputType = InputType.MultiLine(45)),
            DocumentFormEntity("RT/RW", "ketua_rt_rw"),
            DocumentFormEntity("Nomor Surat Keterangan dari Ketua RT/RW", "nomor_surat_rt_rw"),
            DocumentFormEntity("Tanggal Surat Keterangan dari Ketua RT/RW", "tanggal_surat_rt_rw"),
            DocumentFormEntity("Usaha Yang Dimiliki", "punya_usaha"),
            DocumentFormEntity("Keperluan Surat Usaha", "keperluan", inputType = InputType.MultiLine(70)),
            DocumentFormEntity("Tanggal Tanda Tangan", "tanggal_ttd", today),
            DocumentFormEntity("Nama Kepala Desa", "nama_kades"),
        )),
        DocumentEntity("Surat Keterangan Domisili", "surat_keterangan_domisili.pdf", listOf(
            DocumentFormEntity("Nama", "nama"),
            DocumentFormEntity("Jenis Kelamin", "jenis_kelamin"),
            DocumentFormEntity("Bin/Binti", "bin_binti"),
            DocumentFormEntity("Tempat/tanggal lahir", "tempat_tanggal_lahir"),
            DocumentFormEntity("Agama", "agama"),
            DocumentFormEntity("Warganegara", "warga_negara"),
            DocumentFormEntity("No. KTP/NIK", "nik"),
            DocumentFormEntity("Pekerjaan", "pekerjaan"),
            DocumentFormEntity("Alamat", "alamat", inputType = InputType.MultiLine(35)),
            DocumentFormEntity("RT/RW", "ketua_rt_rw"),
            DocumentFormEntity("Nomor", "nomor_surat_rt_rw"),
            DocumentFormEntity("Tanggal", "tanggal_surat_rt_rw"),
            DocumentFormEntity("Keperluan", "keperluan", inputType = InputType.MultiLine(70)),
            DocumentFormEntity("Tanggal Tanda Tangan", "tanggal_ttd", today),
            DocumentFormEntity("Nama Kepala Desa", "nama_kades"),
            DocumentFormEntity("Nama Pemohon", "nama_pemohon"),
            )),
        DocumentEntity("Surat Keterangan Domisili Usaha", "surat_keterangan_domisili_usaha.pdf", listOf(
            DocumentFormEntity("Nama Lengkap", "nama"),
            DocumentFormEntity("Jenis Kelamin", "jenis_kelamin"),
            DocumentFormEntity("Tempat/Tanggal Lahir", "tempat_tanggal_lahir"),
            DocumentFormEntity("Kewarganegaraan", "warga_negara"),
            DocumentFormEntity("No. KTP/NIK", "nik"),
            DocumentFormEntity("Pekerjaan", "pekerjaan"),
            DocumentFormEntity("Alamat", "alamat", inputType = InputType.MultiLine(55)),
            DocumentFormEntity("RT", "ketua_rt"),
            DocumentFormEntity("RW", "ketua_rw"),
            DocumentFormEntity("Nomor", "nomor_surat_rt_rw"),
            DocumentFormEntity("Tanggal", "tanggal_surat_rt_rw"),
            DocumentFormEntity("Nama Perusahaan", "nama_perusahaan"),
            DocumentFormEntity("Nama Pemilik", "pemilik_perusahaan"),
            DocumentFormEntity("Alamat Perusahaan", "alamat_perusahaan"),
            DocumentFormEntity("Jenis Usaha", "jenis_perusahaan"),
            DocumentFormEntity("Status Perusahaan", "status_perusahaan"),
            DocumentFormEntity("Jumlah Karyawan", "jumlah_karyawan"),
            DocumentFormEntity("Luas Tempat Usaha", "luas_tempat_usaha"),
            DocumentFormEntity("Waktu Usaha", "waktu_usaha"),
            DocumentFormEntity("Keperluan Surat Domisili Usaha", "keperluan"),
            DocumentFormEntity("Tanggal Tanda Tangan", "tanggal_ttd", today),
            DocumentFormEntity("Nama Kepala Desa", "nama_kades"),
            )),
        DocumentEntity("Surat Keterangan Domisili Instansi", "surat_keterangan_domisili_instansi.pdf", listOf(
            DocumentFormEntity("Nama Lengkap", "nama"),
            DocumentFormEntity("Jenis Kelamin", "jenis_kelamin"),
            DocumentFormEntity("Tempat/Tanggal Lahir", "tempat_tanggal_lahir"),
            DocumentFormEntity("Kewarganegaraan", "warga_negara"),
            DocumentFormEntity("No. KTP/NIK", "nik"),
            DocumentFormEntity("Pekerjaan", "pekerjaan"),
            DocumentFormEntity("Alamat", "alamat", inputType = InputType.MultiLine(55)),
            DocumentFormEntity("RT", "ketua_rt"),
            DocumentFormEntity("RW", "ketua_rw"),
            DocumentFormEntity("Nomor", "nomor_surat_rt_rw"),
            DocumentFormEntity("Tanggal", "tanggal_surat_rt_rw"),
            DocumentFormEntity("Nama Instansi", "nama_instansi"),
            DocumentFormEntity("Nama Pemilik", "pemilik_instansi"),
            DocumentFormEntity("Alamat Instansi", "alamat_instansi"),
            DocumentFormEntity("Jenis Instansi", "jenis_instansi"),
            DocumentFormEntity("Status Instansi", "status_instansi"),
            DocumentFormEntity("Jumlah Anggota", "jumlah_anggota"),
            DocumentFormEntity("Tempat Instansi", "tempat_instansi"),
            DocumentFormEntity("Waktu", "waktu_instansi"),
            DocumentFormEntity("Keperluan Surat Domisili Usaha", "keperluan"),
            DocumentFormEntity("Tanggal Tanda Tangan", "tanggal_ttd", today),
            DocumentFormEntity("Nama Kepala Desa", "nama_kades"),
        )),
    )

    val suratPengantarList = listOf(
        DocumentEntity("Surat Pengantar Umum", "surat_pengantar_umum.pdf", listOf(
            DocumentFormEntity("Nama Lengkap", "nama"),
            DocumentFormEntity("Tempat/Tanggal Lahir", "tempat_tanggal_lahir"),
            DocumentFormEntity("Warga Negara", "warga_negara"),
            DocumentFormEntity("Agama", "agama"),
            DocumentFormEntity("Pekerjaan", "pekerjaan"),
            DocumentFormEntity("Tempat Tinggal", "alamat"),
            DocumentFormEntity("NIK", "nik"),
            DocumentFormEntity("No. KK", "no_kk"),
            DocumentFormEntity("Keperluan", "keperluan", inputType = InputType.MultiLine(50)),
            DocumentFormEntity("Berlaku Dari", "berlaku_dari"),
            DocumentFormEntity("Berlaku Hingga", "berlaku_hingga"),
            DocumentFormEntity("Keterangan Lain", "keterangan", inputType = InputType.MultiLine(50)),
            DocumentFormEntity("Nama Pemohon", "nama_pemohon"),
            DocumentFormEntity("Tanggal Tanda Tangan", "tanggal_ttd", today),
            DocumentFormEntity("Nama Kepala Desa", "nama_kades"),
            )),
        DocumentEntity("Surat Pengantar Ijin Keramaian", "surat_pengantar_ijin_keramaian.pdf", listOf(
            DocumentFormEntity("Nama Lengkap", "nama"),
            DocumentFormEntity("Tempat/Tanggal Lahir", "tempat_tanggal_lahir"),
            DocumentFormEntity("Jenis Kelamin", "jenis_kelamin"),
            DocumentFormEntity("Agama", "agama"),
            DocumentFormEntity("Kewarganegaraan", "warga_negara"),
            DocumentFormEntity("NIK", "nik"),
            DocumentFormEntity("Pekerjaan", "pekerjaan"),
            DocumentFormEntity("Alamat Pemohon", "alamat"),
            DocumentFormEntity("Maksud Keramaian", "maksud_keramaian"),
            DocumentFormEntity("Tanggal Penyelenggaraan", "tanggal_keramaian"),
            DocumentFormEntity("Waktu Penyelenggaraan", "waktu_keramaian"),
            DocumentFormEntity("Tempat Penyelenggaraan", "tempat_keramaian"),
            DocumentFormEntity("Jenis Hiburan", "jenis_hiburan"),
            DocumentFormEntity("Jumlah Undangan", "jumlah_undangan"),
            DocumentFormEntity("Ketua RT Surat Pernyataan", "ketua_rt"),
            DocumentFormEntity("Nomor Surat Pernyataan", "nomor_surat_rt"),
            DocumentFormEntity("Tanggal Surat Pernyataan", "tanggal_surat_rt"),
            DocumentFormEntity("Nama Pemohon", "nama_pemohon"),
            DocumentFormEntity("Tanggal Tanda Tangan", "tanggal_ttd", today),
            DocumentFormEntity("Nama Kepala Desa", "nama_kades"),
        )),
        DocumentEntity("Surat Pengantar SKCK", "surat_pengantar_skck.pdf", listOf(
            DocumentFormEntity("Nama Lengkap", "nama"),
            DocumentFormEntity("Jenis Kelamin", "jenis_kelamin"),
            DocumentFormEntity("Tempat/Tanggal Lahir", "tempat_tanggal_lahir"),
            DocumentFormEntity("Warga Negara", "warga_negara"),
            DocumentFormEntity("Agama", "agama"),
            DocumentFormEntity("Status Perkawinan", "status_kawin"),
            DocumentFormEntity("No. KTP/NIK", "nik"),
            DocumentFormEntity("Pekerjaan", "pekerjaan"),
            DocumentFormEntity("Alamat", "alamat", inputType = InputType.MultiLine(55)),
            DocumentFormEntity("Ketua RT/RW dari Surat Keterangan", "ketua_rt_rw"),
            DocumentFormEntity("Nomor Surat Keterangan", "nomor_surat_rt_rw"),
            DocumentFormEntity("Tanggal Surat Keterangan", "tanggal_surat_rt_rw"),
            DocumentFormEntity("No. Reg", "no_reg"),
            DocumentFormEntity("Tanggal SKCK", "tanggal_skck"),
            DocumentFormEntity("Nama Camat Gladagsari", "nama_camat"),
            DocumentFormEntity("NIP Camat Gladagsari", "nip_camat"),
            DocumentFormEntity("Nama Pemohon", "nama_pemohon"),
            DocumentFormEntity("Tanggal Tanda Tangan", "tanggal_ttd", today),
            DocumentFormEntity("Nama Kepala Desa", "nama_kades"),
        ))
    )
}